print("**********************************************")
print("**********************************************")
print("**                                          **")
print("**     Traffic Is Jammed At Next Signal     **")
print("**                                          **")
print("**      Kindly take the other route to      **")
print("**          reach your destination...       **")
print("**                                          **")
print("**              THANK YOU!!!                **")
print("**                                          **")
print("**********************************************")
print("**********************************************")